[workspace]
members = ["private_deposit"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["TACEO GmbH <hello@taceo.io>"]
homepage = "https://www.taceo.io"
repository = "https:://github.com/TaceoLabs/private_deposit"
license = "MIT OR Apache-2.0"
publish = false
readme = "./README.md"

[workspace.dependencies]

[profile.profiling]
inherits = "bench"
debug = true
lto = "thin"
