[workspace]
members = ["private_deposit"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
authors = ["TACEO GmbH <hello@taceo.io>"]
homepage = "https://www.taceo.io"
repository = "https:://github.com/TaceoLabs/private_deposit"
license = "MIT OR Apache-2.0"
publish = false
readme = "./README.md"

[workspace.dependencies]
ark-bn254 = "^0.5.0"
ark-ff = "^0.5.0"
ark-groth16 = "0.5.0"
ark-serialize = { version = "^0.5.0", features = ["derive", "std"] }
clap = { version = "4.4.8", features = ["derive"] }
co-circom = { version = "0.9.0", git = "https://github.com/TaceoLabs/co-snarks", branch = "rw/r1cs" }
co-noir = { version = "0.6.0", git = "https://github.com/TaceoLabs/co-snarks", branch = "rw/r1cs" }
co-ultrahonk = { version = "0.5.0", git = "https://github.com/TaceoLabs/co-snarks", branch = "rw/r1cs" }
eyre = "0.6.12"
figment = { version = "0.10.19", features = ["toml", "env"] }
itertools = "0.14.0"
mpc-core = { version = "0.9.0", git = "https://github.com/TaceoLabs/co-snarks", branch = "rw/r1cs" }
mpc-net = { version = "0.4.0", git = "https://github.com/TaceoLabs/co-snarks", branch = "rw/r1cs", features = [
    "local",
] }
noirc-artifacts = { version = "1.0.0-beta.6", git = "https://github.com/noir-lang/noir/", tag = "v1.0.0-beta.6", package = "noirc_artifacts" }
rand = "0.8.5"
rand_chacha = "0.3"
rustls = "0.23.15"
oblivious_map = { path = "../oblivious_map/oblivious_map" } # rw/r1cs branch TODO this is not clean
oblivious_map_proof = { path = "../oblivious_map/oblivious_map_proof" } # rw/r1cs branch  TODO this is not clean
serde = { version = "1.0.193", features = ["derive", "rc"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }


[profile.profiling]
inherits = "bench"
debug = true
lto = "thin"
