amount = "42"
receiver_new_r = "17331892253437890031251862029044676496972846111818735601643271411076390561963"
receiver_old_balance = "127"
receiver_old_r = "6076474130078401668797181001268877600600501053455794295859629390507099416475"
sender_new_r = "13672605466149661679687937823998309560321718953472306268121269974081378644713"
sender_old_balance = "184"
sender_old_r = "10408785098064733238065653085068623418230004048829819170608976931956738169970"
amount_r = "4402497318906117673815837614606554259646836716453631141703646256899230636401"
