amount = "42"
new_r = "17331892253437890031251862029044676496972846111818735601643271411076390561963"
old_balance = "127"
old_r = "6076474130078401668797181001268877600600501053455794295859629390507099416475"
amount_r = "4402497318906117673815837614606554259646836716453631141703646256899230636401"
