[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable optimizer
optimizer = true

# How aggressively to optimize (higher = more runtime-opt, bigger bytecode)
optimizer_runs = 10000000

via_ir = true
memory_limit = 1073741824
gas_limit = "18446744073709551615"
