amount = "42"
new_r = "13672605466149661679687937823998309560321718953472306268121269974081378644713"
old_balance = "184"
old_r = "10408785098064733238065653085068623418230004048829819170608976931956738169970"
amount_r = "4402497318906117673815837614606554259646836716453631141703646256899230636401"
